name: Publish DEB Package

on:
  push:
    tags:
      - '*'

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Replace version with tag
        run: |
          sed -E -i 's|VERSION "[0-9.]+"|VERSION "${{ steps.get_version.outputs.VERSION }}"|' CMakeLists.txt

      - name: Build and Create DEB
        run: |
          mkdir build
          cd build
          cmake ../
          make
          cpack

      - name: Replace binary version with tag
        run: |
          mv build/crc32csum build/crc32csum-${{ steps.get_version.outputs.VERSION }}-linux-amd64

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/crc32csum_${{ steps.get_version.outputs.VERSION }}_amd64.deb
            build/crc32csum-${{ steps.get_version.outputs.VERSION }}-linux-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-mac:
    runs-on: macos-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Replace version with tag
        run: |
          sed -E -i '' -e 's|VERSION "[0-9.]+"|VERSION "${{ steps.get_version.outputs.VERSION }}"|' CMakeLists.txt

      - name: Build binary
        run: |
          mkdir build
          cd build
          cmake ../
          make

      - name: Replace binary version with tag
        run: |
          mv build/crc32csum build/crc32csum-${{ steps.get_version.outputs.VERSION }}-darwin-amd64

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/crc32csum-${{ steps.get_version.outputs.VERSION }}-darwin-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}